name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.salouaa }}
          password: ${{ secrets.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 }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.salouaa }}/ann-diabetes-api:latest
